# Generated by Django 5.1.2 on 2024-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('salt_composition', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=50)),
                ('product_manufactured', models.CharField(max_length=100)),
                ('medicine_desc', models.TextField()),
                ('side_effects', models.TextField()),
                ('drug_interactions', models.TextField()),
            ],
        ),
    ]
